---
- name: Check if EPEL repo is already configured.
  stat: path={{ epel_repofile_path }}
  register: epel_repofile_result

- debug:
    msg: "{{ epel_repofile_result }}"

- name: Install EPEL repo.
  yum:
    name: "{{ epel_repo_url }}"
    state: present
  register: result
  #until: '"failed" not in result'
  #retries: 5
  delay: 10
  become: true
  when: not epel_repofile_result.stat.exists

- name: Import EPEL GPG key.
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present
  when: not epel_repofile_result.stat.exists
  become: true
  ignore_errors: "{{ ansible_check_mode }}"

- name: Install basic packages 
  yum: 
    state: present 
    name: "{{ base_rpms }}"
  become: true

- name: Install additionals rpms 
  yum: 
    state: present 
    name: "{{ additionals_rpms }}"
  become: true
  when: additionals_rpms is defined

- name: Disable firewalld
  service:
    name: firewalld
    enabled: no
  become: true

- name: Stop firewalld 
  service: 
    name: firewalld 
    state: stopped
  become: true
 
- name: Setup motd 
  copy: 
    src: files/motd
    dest: /etc/motd
    owner: root
    group: root
    mode: 0644
  become: true


