---
putit_build_agent_user: 'tools'
ssh_users:
    - name: 'tools'
      group: 'tools' 
      groups: 'wheel'
      ssh_keys:
        - ssh_keys/tomek_rsa.pub
        - ssh_keys/tomek2_rsa.pub
        - ssh_keys/mateusz_proddata_rsa.pub  
        - ssh_keys/depapp_rsa.pub 

