- name: Clone putit-core
  git:
    repo: "git@github.com:skowpio/deployer-services.git"
    dest: "{{ putit_core_deploy_dir }}"
    key_file: "/home/{{ deployer_app_user }}/.ssh/id_rsa"
    clone: yes
    force: yes
    version: "{{ putit_core_deploy_branch }}"
    accept_hostkey: true
  become: true
  become_user: "{{ deployer_app_user }}"

- name: Clone putit-auth
  git:
    repo: "git@github.com:skowpio/deployer-auth.git"
    dest: "{{ putit_auth_deploy_dir }}"
    key_file: "/home/{{ deployer_app_user }}/.ssh/id_rsa"
    clone: yes
    force: yes
    version: "{{ putit_auth_deploy_branch }}"
    accept_hostkey: true
  become: true
  become_user: "{{ deployer_app_user }}"
