- name: Check jo is installed
  stat:
    path: /usr/local/bin/jo
  register: is_jo

- name: Clone jo repo tool
  git:
    repo: 'git://github.com/jpmens/jo.git'
    dest: /usr/src/jo
    clone: yes
    update: yes
  when: "not {{ is_jo.stat.exists }}"

- name: Compile jo
  shell: |
    autoreconf -i
    ./configure
    make check
    make install
  args:
    chdir: /usr/src/jo
  become: true
  when: "not {{ is_jo.stat.exists }}"
