- include: install_jq.yml
  tags: install_jq

- include: install_jo.yml
  tags: install_jo

- include: install_venvs.yml
  tags: install_venvs

# now from rpm
#- include: install_bats.yml
#  tags: install_bats

# dont know if we need it
#- name: Register all postgresql binaries 
#  shell: "ls /usr/pgsql-{{ postgresql_major_version }}/bin"
#  register: registered_postgresql_tools

#- name: Link postgresql pg_config - ansible path limitation
#  file: 
#    src:  "/usr/pgsql-{{ postgresql_major_version }}/bin/pg_config"
#    dest: "/bin/pg_config"
#    owner: root
#    group: root
#    state: link
