---
putit_build_agent_user: 'tools'
ssh_users:
    - name: 'depapp'
      group: 'depapp' 
      groups: 
        - wheel
        - docker
      shell: '/bin/bash'
      sudoers:
          all: true
          password_less: true
      ssh_keys:
        - ssh_keys/krzysztofk_rsa.pub
        - ssh_keys/mateuszw_rsa.pub
        - ssh_keys/piotrs_rsa.pub  
        - ssh_keys/tools_rsa.pub
        - ssh_keys/depapp_rsa.pub
